apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-api
spec:
  selector:
    matchLabels:
      name: database-api
  template:
    metadata:
      labels:
        name: database-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: database-api
        image: glgelopfalcon/database-api:v1
        env:
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: MONGO_CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: database-api
spec:
  selector:
    name: database-api
  ports:
  - port: 80
    targetPort: 80