apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-cache
spec:
  selector:
    matchLabels:
      name: stats-cache
  template:
    metadata:
      labels:
        name: stats-cache
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: cache
        image: redis:5-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: stats-cache
spec:
  selector:
    name: stats-cache
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-queue
spec:
  selector:
    matchLabels:
      name: stats-queue
  template:
    metadata:
      labels:
        name: stats-queue
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: queue
        image: rabbitmq:3-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: stats-queue
spec:
  selector:
    name: stats-queue
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-worker
spec:
  selector:
    matchLabels:
      name: stats-worker
  template:
    metadata:
      labels:
        name: stats-worker
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: stats-worker
        image: glgelopfalcon/stats-worker:v1
        env:
        - name: STATS_QUEUE_URI
          value: amqp://stats-queue
        - name: REDIS_HOST
          value: stats-cache
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-api
spec:
  selector:
    matchLabels:
      name: stats-api
  template:
    metadata:
      labels:
        name: stats-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: stats-api
        image: glgelopfalcon/stats-api:v1
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /hello
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: stats-api
spec:
  selector:
    name: stats-api
  ports:
  - port: 80
    targetPort: 80